### ISSUE TITLE
Remove AMP support

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/fb-instant-articles#1010]
Now that an [AMP plugin](https://github.com/ampproject/amp-wp) exists, having FBIA create AMP is unnecessary.

it would be good to remove this feature.

**Comment by jerclarke** [comment]
It existed before AMP support was added to this IA plugin, in fact I already had it implemented because it was a much easier process than this plugin, so I ended up running them both. 

Not sure why AMP support would be removed from this plugin now, though I never used it and it's probably bad to use it, because AMP supports much more flexibility in terms of output (both systems have their tradeoffs of course, but all else equal, you are better off having a great AMP theme for your site than living with a clone of your IA)

**Comment by paulschreiber** [comment]
* This plugin supports a small subset of AMP.
* It'd be a poor use of time to keep updating this plugin's AMP support as AMP evolves.
* More code = more tests = more complexity. Removing unnecessary code will make this easier to maintain.

**Comment by jerclarke** [comment]
Agree with all your points. Considering this plugin barely works at it's core job, having it support AMP too never seemed like a great idea. 

For the sake of argument, here's the other side:

- Once someone has gotten this plugin working finally, having an AMP version "for free" is a great value.
- Some users weren't going to set up the AMP plugin anyway, it's a big project too, and basing it on this plugin is a decent fit for them.

**Comment by paulschreiber** [comment]
Good news: the new version of the AMP plugin (1.0) will give you AMP "for free" as well.
