### ISSUE TITLE
No rules defined for <div class="wp-block-image"> in the context of InstantArticle

### ISSUE THREAD

**Issue by ilearning101** [Automattic/fb-instant-articles#1041]
No rules defined for <div class="wp-block-image"> in the context of InstantArticle

Been searching for this issues for hours, didn't see any highlight here

Anyone can suggest how to encounter this issue please?

**Comment by 81adil** [comment]
Please share the solution of No rules defined for above question

**Comment by mrwindowsx** [comment]
Same here, found an error like this using FB instant article plugin with wp, please fix

**Comment by keyinora** [comment]
This is still happening, in WP 5.5.1. It appears the Gutenberg Image Blocks is what it thinks is the plugin. Is there a plan to fix this?

**Comment by keyinora** [comment]
I did some testing as I found that some of my post didn't have this issue, but had image blocks used.

The issue comes up, when you apply an alignment to a block.

It by default is only wrapped in a <figure>, but the moment you apply an alignment, it add a "<div class="wp-block-image">" around the element.

I hope this helps

**Comment by keyinora** [comment]
Fix till this can be corrected in the plugin.

{
    "rules": [{
		"class": "PassThroughRule", "selector": "div.wp-block-image"
    }]
}
