### ISSUE TITLE
Support for HeaderSubTitleRule

### ISSUE THREAD

**Issue by partcoffee** [Automattic/fb-instant-articles#294]
Just checking to see if there's any support for the subtitle rule without physically moving the h2 into the header? Ideally through custom transformer rules.

**Comment by FewKinG** [comment]
If I understand your request correctly, you want to use content in the InstantArticle context as header subtitle. I see three ways in which you can achieve this.

### 1. Custom Transformer Rule with custom content

You can ensure, that the content you want to include in the subtitle is part of the IA content so that you can select it with custom transformer rules. One way you could do this by implementing the `instant_articles_content` filter: 

```
add_filter ( 'instant_articles_content', 'filter_ia_content' );

function filter_ia_content ( $content ) {
	return '<div class="header"><div class="headerSubTitle">example subtitle</div></div>' . $content ;
}
```

You can then add these two transformer rules to transform this content into a subheader:

```
{
  "class": "HeaderRule",
  "selector": ".header"
},
{
  "class": "HeaderSubTitleRule",
  "selector": ".headerSubTitle"
}
```

### 2. Use the plugin's subtitle filter

This plugin already provides a filter to get the posts subtitle. Only thing is, that it's currently not used, i.e. the subtitle is never actually added to the header. I made a fix for this in this branch of my plugin fork at https://github.com/FewKinG/facebook-instant-articles-wp/tree/header_subtitle
If you want to implement it yourself, you can check out my branch or add this to the file `class-instant-articles-post.php` to the `to_instant_article` method after the header has been initialized:

```
if ( $this->has_subtitle() ) {
    $header->withSubTitle ( $this->get_the_subtitle() ) ;
}
```

Then, in your own code, you can use the filter to provide the subtitle content:

```
add_filter ( 'instant_articles_subtitle', 'filter_ia_subtitle' ) ;

function filter_ia_subtitle ( $subtitle ) {
	return 'example subtitle' ;
}
```

### 3. Write a custom rule class

In theory, it is possible to extend the set of rules provided by the Facebook IA SDK to include a fitting rule that is allowed in the InstantArticle context.
This is not currently supported by this plugin. However, I create a branch in my fork that allows the extension of the default SDK classes and for test purposes I added a SubTitleRule class that does what you want:
https://github.com/FewKinG/facebook-instant-articles-wp/tree/header_subtitle_rule
You can review the code in the rule class file `fbaddons/Facebook/InstantArticles/Transformer/Rules/SubTitleRule.php`.

You can then create a custom transformer rule without the need of it being in the Header context like so (referring to solution 1):

```
{
  "class": "SubTitleRule",
  "selector": ".headerSubTitle"
}
```

Although I see the reasoning behind extending the default rule set, I don't like this third solution in this particular case and consider the 1st and 2nd ones to be cleaner.

**Comment by everton-rosario** [comment]
@partcoffee Have this solved your issue?

**Comment by partcoffee** [comment]
I did mange to get the second solution working eventually, but I have yet to push it to our production build. While I don't like altering the core version of the plugin, it definitely gets the job done.

Currently working on a solution to remove the first sentence from the default content completely, and return it as a subtitle.

**Comment by MartinN3** [comment]
I cant provide subtitle content since i dont know post ID in that filter, could you help me with that ?

**Comment by partcoffee** [comment]
@MartinN3 Could you provide some more details on that? Which solution are you trying to work with?

**Comment by ManuelOcc** [comment]
Hi! 
I checked the documentation and it says there is a _HeaderSubTitleRule_ implemented. 
I tried adding the custom rule, which for me is: 
```
{
  "class": "HeaderTitleRule ",
  "selector": "p.td-post-sub-title"
}
```

But that's not making any difference. I also tried using HeaderTitleRule, not working too. 
And then I tried to put it directly into the json rules file, but nothing happens. 

It seems like the rule is **completely ignored**.. 

thanks in advance!

**Comment by apollosk** [comment]
@everton-rosario I have the same problem as @ManuelOcc. Can you help us out?
Here's [an article with subtitle on our website](http://www.queer.mk/sara-dzesika-parker-navesti-deka-se-krchka-tretoto-prodolzenie-na-filmot-seksot-i-gradot-18-10-2016.html).

**Comment by OtherF** [comment]
I use ```excerpt``` on my site and want to transform it to ```subtitle```.
In the code it looks like:
```html
<div class="entry-headline">
<p>Some Excerpt text here</p>
</div>
```

I created a Rule for Instant Article:
```
{
  "class": "HeaderSubTitleRule ",
  "selector": "div.entry-headline"
}
```
But the rule **is ignored**.

Don't know how to handle this.

**Comment by OtherF** [comment]
Ok, the 2nd solution of @FewKinG works, but I want to use ```excerpt``` as ```subtitle```.
I tried add this code in ```function.php```:
```
function filter_ia_subtitle ( $subtitle ) {
    $excerpt = get_post()->post_excerpt;
    
    return $excerpt;
}
```
But without success :(

**Comment by OtherF** [comment]
Ok, seems resolved.
I've just copied  the content from the ```public function get_the_excerpt()``` to ```public function get_the_subtitle()```:
```
public function get_the_subtitle() {
		// If we have already been through this function, we’ll have the result stored here
		if ( ! is_null( $this->_subtitle ) ) {
			return $this->_subtitle;
		}
        
        $post = get_post( $this->get_the_id() );
		// This should ideally not happen, but it may do so if someone tampers with the query.
		// Returning the same protected post excerpt as "usual" may help them identify what’s going on.
		if ( post_password_required( $this->get_the_ID() ) ) {
			return __( 'There is no excerpt because this is a protected post.' );
		}
		// Make sure no “read more” link is added.
		add_filter( 'excerpt_more', '__return_empty_string', 999 );
		/**
		 * Apply the default WP Filters for the post excerpt.
		 *
		 * @since 0.1
		 *
		 * @param string  $post_excerpt  The post excerpt.
		 */
		$subtitle = apply_filters( 'get_the_excerpt', $post->post_excerpt );
        
		/**
		 * Filter the subtitle for use in instant articles
		 *
		 * @since 0.2
		 *
		 * @param string                 $subtitle              The current subtitle for the post.
		 * @param Instant_Article_Post   $instant_article_post  The instant article post
		 */
		$subtitle = apply_filters( 'instant_articles_subtitle', $subtitle, $this );
		$this->_subtitle = $subtitle;
		return $subtitle;
	}
```

**Comment by onlinedev93** [comment]
Hi guys. I am using custom transformer rules. But it isn't working now.
{
  "class": "HeaderSubTitleRule ",
  "selector": "p.td-post-sub-title"
}
Please help me.
