### ISSUE TITLE
Embed filters affecting content outside of Instant Articles feeds

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/fb-instant-articles#337]
The FBIA plugin adds several filters. Example: in `themes/vip/plugins/facebook-instant-articles-2.11/embeds.php`, on line 54:

```
add_filter( 'embed_oembed_html', 'instant_articles_embed_oembed_html', 10, 4 );
```

In the function instant_articles_embed_get_html(), the HTML gets wrapped in a div like so: 

```
$html = sprintf( '<div class="embed">%s</div>', $html );
```

This code currently affects content in regular web views. It should only affect content in instant articles feeds.

**Comment by kevinlisota** [comment]
I'm seeing this as well. The plugin's filters should not alter oembed handling or filters for front-end display on WP, and it shouldn't be inserting content there either. Need to restrict this oembed handling to plugin-related API calls or feeds only.

**Comment by everton-rosario** [comment]
@paulschreiber @kevinlisota Are you guys experiencing malfunctioning because of the filters?

We need this so the transformer can have any oembed content transformed int "op-interactive".

Do you guys have any fix for this?

Can you provide more info/debuggable content so we can reproduce the same issues you are facing? So we can try another solution for the oembeds.

Thanks for your inputs. 
@paulschreiber sorry for the long time to act on this issue.

**Comment by kevinlisota** [comment]
Reproducing this is easy. Create an article with an oembed(i.e. YouTube video or something). Turn on the plugin and view the page source for that article on WP front-end. Now turn off the plugin and view the page source again. The oembed will be wrapped with `<div class="embed">`. Essentially your plugin is hooking in to the `embed_oembed_html` filter wherever it is used, not just where it is needed which is in the context of your plugin.

I think you should be able to add the `embed_oembed_html` filter right before you need it, then immediately remove it so that it doesn't hook into other uses. I think (but haven't tested), that it might be right before `the_content` filter call that you make in class-instant-articles-post.php, but I'd have to dig in and see where the oembed filter is actually firing in WP.

I actually have a similar concern with the call to `remove_all_filters( 'embed_oembed_html' )` in embeds.php. From the look of it, I think that the moment the plugin loads, it removes anyone else who is hooked to `embed_oembed_html`, potentially affecting the front-end WP content in addition to what your generator does. Once again, this should only be called when you are working with IA content, not the HTML generated for the WP front-end.

We don't use it, but I know that Jetpack has a wrapping function for responsive videos that you can enable with `add_theme_support`. It looks like this plugin would affect that. I have a couple other plugins that hook to that filter as well.

**Comment by everton-rosario** [comment]
@kevinlisota Actually we need to wrap any oembed, so we will wrap them as:
<figure class="op-interactive">
    <iframe>
        ... // all content of the oembed
    </iframe>
</figure>

So youtube and any other oembed should work like this.

What we need to understand is what actually broke because of the wrapping <div>?

**Comment by kevinlisota** [comment]
I get that you need to wrap any oembed to generate IA content and send to FB. But that needs to be done in a way that doesn't drop the wrapper into the HTML source for a regular web view.

We noticed it when the structure of the page changed, and CSS rules that we were applying to oembeds weren't working because they were looking for a more specific selector structure, which now had a new div and class involved.

We do our own wrapping of oembeds for styling and resizing, and this plugin affected that structure. I'm sure other sites may have similar, and other plugins may alter oembed structure as well. (Storyform is one that I know does)

It is fine that you add a wrapper to the oembeds while processing the content for IA, but that is unrelated to the content that should be output to a regular web view. In fact, I would say that unless a plugin is intentionally meaning to alter the web display of a post, it should never alter the post content for web display. Rather it should apply any filters it needs when it needs them, and then remove them when done so that it doesn't remain hooked to other instances of the filter that will affect the HTML generated for a web view.

@paulschreiber how was this affecting your site?

**Comment by everton-rosario** [comment]
@kevinlisota Thanks for your input.

We do have a line on our plugin that kills the filtering of oembed, and that might be breaking the part of your wrapping. Regarding the CSS, do you apply any rules that need to be on the root?

Can you erase the line below on this [file](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/embeds.php) and test, please?
`remove_all_filters( 'embed_oembed_html' );`

Also you could change the CSS style selectors so you wont rely on an "exact" structure. If you need some help with this CSS, post it here and I can try to help you.


@diegoquinteiro and I are trying to create the effect of wrapping the content, without modifying the web HTML. But it will take few more weeks to have it ready.
Hope you can work around this and make it work on your side, @kevinlisota .

**Comment by rinatkhaziev** [comment]
`instant_articles_before_transform_post` seems appropriate for adding IA specific filters and 
`instant_articles_after_transform_post` for cleanup

**Comment by kevinlisota** [comment]
I believe this is a duplicate of #249

**Comment by everton-rosario** [comment]
This is being worked on PR #401

**Comment by mikeselander** [comment]
Hey folks, catching up on this as it looks like it's still an open issue. Anything hooked to `embed_oembed_html ` is still getting stripped even outside of FBIA. 

I see PR #401 referenced, but it was closed in favor of #457, however #457 will not address the issue identified in this Issue. 

Do we need another PR to address this?

**Comment by dashaluna** [comment]
Hey guys, also pinging to see what's the status with this? Thanks.

**Comment by paulgibbs** [comment]
Pinging again. Causing unit test failures on a client project.

**Comment by dashaluna** [comment]
Hey everyone, this is getting a bit of priority for us.. This issue was open Jun 2016 - any movement on this at all?

**Comment by rinatkhaziev** [comment]
We should probably implement the same approach as in 2aec674 which is
merged into master already

**Comment by mikeselander** [comment]
Why was this closed? Has this issue been fixed?

**Comment by timjacobi** [comment]
@mikeselander My bad, I had too many tabs open.

**Comment by jakeparis** [comment]
@timjacobi Sure.
1. Install this plugin, as well as [Responsive Video Embeds](https://wordpress.org/plugins/responsive-video-embeds/). Don't activate either.
1. Create a new post with a youtube url in it. When you view the page (normal web view), notice the video is not responsive. 
1. Activate Responsive Video Embeds, and view your page. You'll notice the video is now responsive (because the RVE plugin is using the _embed_oembed_html_ hook to add a wrapper tag). 
1. Activate Facebook Instant Articles plugin and see that the youtube video is no longer responsive. This is beause this Instant Articles plugin is not apparently allowing other plugins to hook on the _embed_oembed_html_ hook.
