### ISSUE TITLE
No rules defined for <div class="wp-caption alignleft"> in the context of InstantArticle

### ISSUE THREAD

**Issue by ellemcgann** [Automattic/fb-instant-articles#883]
Hi, when I publish articles, I get warnings for each image posting with the error:

"No rules defined for <div class="wp-caption alignleft"> in the context of InstantArticle"

I've tried to use the passover/ignore rule custom transformer rule and it doesn't work (just get the same error as above), and even if it did work, wouldn't that just make image captions not display? I WANT/need them to display. 

Please can somebody help me? I know nothing about programming and this is SO confusing, I've read so many guides but for me nothing is working.

I just want the caption to work. Thanks

<img width="800" alt="screen shot 2018-02-25 at 15 42 03" src="https://user-images.githubusercontent.com/36818855/36643399-84447292-1a42-11e8-83e9-f9393f38532e.png">
<img width="527" alt="screen shot 2018-02-25 at 15 42 14" src="https://user-images.githubusercontent.com/36818855/36643400-8465c262-1a42-11e8-813c-be2734c7b195.png">

**Comment by abramova2018** [comment]
HI bro I had do same problem, but now i know how to resolved this Issue 
firstly you must go to the photos on this articles then click to edit and make photo on the center then 
![screenshot-2018-4-13 edit post my dirasa wordpress](https://user-images.githubusercontent.com/38193533/38760306-7585ac3a-3f72-11e8-8c89-19476fea0ac7.png)
i hope you are understand me 
sorry because im not good in english good luch bro
