### ISSUE TITLE
Allow other plugins to insert their own rules

### ISSUE THREAD

**Issue by mburak** [Automattic/fb-instant-articles#897]
It would be good to add a filter that other plugins can use to insert extra JSON into the transformer rules.

Having to manage external plugin rules inside the IA project is not appropriate and would also make development faster on other plugins that want to implement IA support.

**Comment by jerclarke** [comment]
Proposed properties of this change: 

- Handle [Transformations](https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules) not as JSON, but as PHP data. 
- Store default Transformations as an array inside the plugin, then, only at render time, convert it into JSON for output. 
- Allow plugins/themes to filter the array, adding their own values and removing existing ones. 
   - Alternately add handler functions/methods that do this even more cleanly e.g. 
      - `wp_fb_ia_add_transformation_rule()`
      - `wp_fb_ia_remove_transformation_rule()` 
- Include guides in your documentation for how this can be done
- Encourage plugin developers to implement this API in their plugins, adding IA support without having to have edits made to this project. 
- Encourage individual site developers to implement this API as part of `functions.php` or a custom plugin, so they can control their transformations elegantly through PHP rather than the kind-of-absurd current system where we are expected to edit JSON in a `<textarea>`. 
- On the settings page, have an expandable list, above the `<textarea>` of custom transformations that have been registered by plugins/themes.
- Still allow the JSON option to be used, just add those rules to the array after decoding the JSON. 
- If the JSON setting is valid, show an output of the resulting transformations that matches the one displaying the transformations registered by plugins/themes. 


IMHO getting transformations right is extremely hard in the current system, you could dramatically improve the UX of this experience (which will still be hard, because the  [specifications](https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules) are a brain twister even without the JSON headache) by doing a full review of how they are handled by this plugin. 

That you'll save time and not have to add support for random plugins is icing on the cake. 

Note that making the core change (filterable tranformation rules) will also enable a new type of plugin devoted entirely to supporting IA for a third-party plugin. So e.g. I could create a "Instant Articles Support For Playbuzz" plugin and share it on the repo, if the Playbuzz author wasn't willing to deal with it or didn't reply to requests from various users.
