### ISSUE TITLE
FacebookResponse.php(210)

### ISSUE THREAD

**Issue by Optimusprimekbu** [Automattic/fb-instant-articles#960]
Hello ! Such a problem.
## Steps required to reproduce the problem
#0 /home/prefiksb/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /home/prefiksb/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /home/prefiksb/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /home/prefiksb/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array)
#4 /home/prefiksb/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#5 /home/prefiksb/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(366): Facebook\Facebook->sendRequest('POST', '/?id=https%3A%2...', Array, 'e597fa8ae2f8ede...', NULL, 'v2.10')
#6 /home/prefiksb/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(551): Facebook\Facebook->post('/?id=https%3A%2...', Array, 'e597fa8ae2f8ede...')
#7 /home/prefiksb/public_html/wp-includes/class-wp-hook.php(286): invalidate_scrape_on_update(12622, Object(WP_Post), Object(WP_Post))
#8 /home/prefiksb/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(12644, Array)
#9 /home/prefiksb/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#10 /home/prefiksb/public_html/wp-includes/post.php(3614): do_action('post_updated', 12622, Object(WP_Post), Object(WP_Post))
#11 /home/prefiksb/public_html/wp-includes/post.php(3713): wp_insert_post(Array, false)
#12 /home/prefiksb/public_html/wp-admin/includes/post.php(377): wp_update_post(Array)
#13 /home/prefiksb/public_html/wp-admin/includes/ajax-actions.php(1732): edit_post()
#14 /home/prefiksb/public_html/wp-includes/class-wp-hook.php(286): wp_ajax_inline_save('')
#15 /home/prefiksb/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#16 /home/prefiksb/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#17 /home/prefiksb/public_html/wp-admin/admin-ajax.php(99): do_action('wp_ajax_inline-...')
#18 {main}		
		

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.1.0
* WordPress version: 4.9.7
* PHP version: ea-php55

Without the above information we are not able to debug the issue and will close it.

**Comment by yeah-sir** [comment]
Hi @Optimusprimekbu Can you please send over the input and output HTML from which you got this error? This will help us debug the issue better.

**Comment by mukunds007** [comment]
Facing same issue

**Comment by bertfly01** [comment]
I have the same issue:

#0 /home1/bnur/bayangpilipinas.com/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /home1/bnur/bayangpilipinas.com/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /home1/bnur/bayangpilipinas.com/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /home1/bnur/bayangpilipinas.com/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(225): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array)
#4 /home1/bnur/bayangpilipinas.com/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#5 /home1/bnur/bayangpilipinas.com/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(367): Facebook\Facebook->sendRequest('POST', '/?id=http%3A%2F...', Array, 'EAAfZA37hCYk4BA...', NULL, NULL)
#6 /home1/bnur/bayangpilipinas.com/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(551): Facebook\Facebook->post('/?id=http%3A%2F...', Array, 'EAAfZA37hCYk4BA...')
#7 [internal function]: invalidate_scrape_on_update(1571, Object(WP_Post), Object(WP_Post))
#8 /home1/bnur/bayangpilipinas.com/wp-includes/class-wp-hook.php(286): call_user_func_array('invalidate_scra...', Array)
#9 /home1/bnur/bayangpilipinas.com/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#10 /home1/bnur/bayangpilipinas.com/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#11 /home1/bnur/bayangpilipinas.com/wp-includes/post.php(3647): do_action('post_updated', 1571, Object(WP_Post), Object(WP_Post))
#12 /home1/bnur/bayangpilipinas.com/wp-includes/post.php(3746): wp_insert_post(Array, false)
#13 /home1/bnur/bayangpilipinas.com/wp-admin/includes/post.php(377): wp_update_post(Array)
#14 /home1/bnur/bayangpilipinas.com/wp-admin/post.php(194): edit_post()
#15 {main}

**Comment by shameeryou** [comment]
#0 /home/fp/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /home/fp/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /home/fp/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /home/fp/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 0, Array)
#4 /home/fp/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#5 /home/fp/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(361): Facebook\Facebook->sendRequest('POST', '/?id=https%3A%2...', Array, 'EAARjkbqobW8BAI...', NULL, 'v2.10')
#6 /home/fp/public_html/wp/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(518): Facebook\Facebook->post('/?id=https%3A%2...', Array, 'EAARjkbqobW8BAI...')
#7 /home/fp/public_html/wp/wp-includes/class-wp-hook.php(288): invalidate_scrape_on_update(133003, Object(WP_Post), Object(WP_Post))
#8 /home/fp/public_html/wp/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#9 /home/fp/public_html/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#10 /home/fp/public_html/wp/wp-includes/post.php(4093): do_action('post_updated', 133003, Object(WP_Post), Object(WP_Post))
#11 /home/fp/public_html/wp/wp-includes/post.php(4196): wp_insert_post(Array, false)
#12 /home/fp/public_html/wp/wp-admin/includes/post.php(407): wp_update_post(Array)
#13 /home/fp/public_html/wp/wp-admin/post.php(219): edit_post()
#14 {main}



Source Markup:

<p>കഴിഞ്ഞ ദിവസം കഴിഞ്ഞ ഇന്ത്യ &#8211; ബംഗ്ളദേശ് ഡേ നൈറ്റ് ടെസ്റ്റ് മത്സരം കാണികളുടെ സാന്നിദ്ധ്യം കൊണ്ട് ലോകകപ്പ് ഫൈനലാണെന്ന് തോന്നിയെന്ന് ബി.സി.സി.ഐ പ്രസിഡണ്ട് സൗരവ് ഗാംഗുലി. ഫോണിലെ കാമറയുമെടുത്ത് ഫോട്ടോ എടുക്കുന്ന ആരാധകരെ ചൂണ്ടി കാണിച്ച് ഇത്തരത്തിൽ കാണികളെ നിങ്ങൾ ടെസ്റ്റ് മത്സരങ്ങൾക്ക് കാണാറുണ്ടോ എന്ന് ചോദിച്ച ഗാംഗുലി എന്നാണ് അവസാനമായി ഒരു ടെസ്റ്റ് മത്സരത്തിന് ഇത്രയും കാണികൾ വന്നതെന്നും ചോദിച്ചു.</p>
<p>ബി.സി.സി.ഐ പ്രസിഡന്റായ സൗരവ് ഗാംഗുലിയുടെ ശ്രമം ഫലമായാണ് ബംഗ്ലാദേശിനെതിരായ പരമ്പരയിൽ ഡേ നൈറ്റ് ടെസ്റ്റ് കളിക്കാൻ ബംഗ്ളാദേശ് ക്രിക്കറ്റ് ബോർഡ് സമ്മതിച്ചത്. ബംഗ്ളാദേശിനെതിരായ ഡേ നൈറ്റ് വളരെ മികച്ച അനുഭവമായിരുന്നെന്ന് പറഞ്ഞ ഗാംഗുലി ടെസ്റ്റ് ക്രിക്കറ്റ് ഇതുപോലെയുള്ള നിറഞ്ഞ സ്റ്റേഡിയത്തിൽ കളിക്കണമെന്നും പറഞ്ഞു.</p>
<p>കൊൽക്കത്തയിലെ ഈഡൻ ഗാർഡൻസിൽ നടന്ന ഇന്ത്യയുടെ ആദ്യ ടെസ്റ്റ് കാണികളുടെ പിന്തുണ കൊണ്ട് ശ്രദ്ധേയമായിരുന്നു. മത്സരത്തിന്റെ ആദ്യ നാല് ദിവസത്തേക്കുള്ള ടിക്കറ്റുകൾ മുഴുവനായും വിറ്റ് തീർന്നിരുന്നു.</p>



Transformed Markup

<html>
  <head>
    <link rel="canonical" href="https://fanport.in/cricket/felt-like-world-cup-final-says-ganuly/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.10.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.2.0"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.10.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default"/>
    <meta property="fb:article_style" content="fanport"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="https://fanport.in/wp/wp-content/uploads/2019/11/sourav-ganguly-day-night-test-e1574675552731.jpeg"/>
          <figcaption>Photo: Twitter/@SGanguly99</figcaption>
        </figure>
        <h1>ഡേ നൈറ്റ് ടെസ്റ്റ് ലോകകപ്പ് ഫൈനലാണെന്ന് തോന്നിയെന്ന് സൗരവ് ഗാംഗുലി</h1>
        <time class="op-published" datetime="2019-11-25T15:24:09+00:00">November 25th, 3:24pm</time>
        <time class="op-modified" datetime="2019-11-25T15:30:18+00:00">November 25th, 3:30pm</time>
        <address><a>Staff Reporter</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=593582227668959_593595477667634&adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <p>കഴിഞ്ഞ ദിവസം കഴിഞ്ഞ ഇന്ത്യ – ബംഗ്ളദേശ് ഡേ നൈറ്റ് ടെസ്റ്റ് മത്സരം കാണികളുടെ സാന്നിദ്ധ്യം കൊണ്ട് ലോകകപ്പ് ഫൈനലാണെന്ന് തോന്നിയെന്ന് ബി.സി.സി.ഐ പ്രസിഡണ്ട് സൗരവ് ഗാംഗുലി. ഫോണിലെ കാമറയുമെടുത്ത് ഫോട്ടോ എടുക്കുന്ന ആരാധകരെ ചൂണ്ടി കാണിച്ച് ഇത്തരത്തിൽ കാണികളെ നിങ്ങൾ ടെസ്റ്റ് മത്സരങ്ങൾക്ക് കാണാറുണ്ടോ എന്ന് ചോദിച്ച ഗാംഗുലി എന്നാണ് അവസാനമായി ഒരു ടെസ്റ്റ് മത്സരത്തിന് ഇത്രയും കാണികൾ വന്നതെന്നും ചോദിച്ചു.</p>
      <p>ബി.സി.സി.ഐ പ്രസിഡന്റായ സൗരവ് ഗാംഗുലിയുടെ ശ്രമം ഫലമായാണ് ബംഗ്ലാദേശിനെതിരായ പരമ്പരയിൽ ഡേ നൈറ്റ് ടെസ്റ്റ് കളിക്കാൻ ബംഗ്ളാദേശ് ക്രിക്കറ്റ് ബോർഡ് സമ്മതിച്ചത്. ബംഗ്ളാദേശിനെതിരായ ഡേ നൈറ്റ് വളരെ മികച്ച അനുഭവമായിരുന്നെന്ന് പറഞ്ഞ ഗാംഗുലി ടെസ്റ്റ് ക്രിക്കറ്റ് ഇതുപോലെയുള്ള നിറഞ്ഞ സ്റ്റേഡിയത്തിൽ കളിക്കണമെന്നും പറഞ്ഞു.</p>
      <p>കൊൽക്കത്തയിലെ ഈഡൻ ഗാർഡൻസിൽ നടന്ന ഇന്ത്യയുടെ ആദ്യ ടെസ്റ്റ് കാണികളുടെ പിന്തുണ കൊണ്ട് ശ്രദ്ധേയമായിരുന്നു. മത്സരത്തിന്റെ ആദ്യ നാല് ദിവസത്തേക്കുള്ള ടിക്കറ്റുകൾ മുഴുവനായും വിറ്റ് തീർന്നിരുന്നു.</p>
      <figure class="op-tracker">
        <iframe>
          <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-85738876-1', 'auto');
  ga('send', 'pageview');

</script>
        </iframe>
      </figure>
      <footer>
        <small>Fanport News Media | fanport.in</small>
      </footer>
    </article>
  </body>
</html>

Plugin Version: 4.2.0
Wordpress Version:  5.3
Php Version 7.3

Issue started when facebook detected some unusal activity and logged out from all of my devices.

Issue happens when I publish or update the post
